version: "3"
services:
  mongodb:
    image: mongo:5.0
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ~/apps/mongo:/data/db

  user-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    tty: true

# Si se quiere levantar junto a los otros microservicios, descomentar y tener en cuenta
# que se debe clonar el proyecto de cada microservicio en la carpeta ../

  training-microservice:
    image: training-microservice
    build:
      context: ../training-microservice
      dockerfile: Dockerfile
    volumes:
      - ../training-microservice/app:/app/app
    env_file:
      - ../training-microservice/.env
    ports:
      - ${TRAINING_SERVICE_PORT}:${TRAINING_SERVICE_PORT}
    depends_on:
      - user-microservice
      - mongodb
    tty: true

  goals-microservice:
    image: goals-microservice
    build:
      context: ../goals-microservice
      dockerfile: Dockerfile
    volumes:
      - ../goals-microservice/app:/app/app
    env_file:
      - ../goals-microservice/.env
    ports:
      - ${GOALS_SERVICE_PORT}:${GOALS_SERVICE_PORT}
    depends_on:
      - user-microservice
      - training-microservice
      - mongodb
    tty: true

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    volumes:
      - ../api-gateway/app:/app/app
    env_file:
      - ../api-gateway/.env
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      - user-microservice
      - training-microservice
      - goals-microservice
    tty: true
