services:
  mongodb:
    image: mongo:5.0
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ~/apps/mongo:/data/db

  user_microservice:
    image: user_microservice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/root/app
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - mongodb