services:
  mongodb:
    image: mongo:5.0
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ~/apps/mongo:/data/db

  user_microservice:
    image: user_microservice
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    tty: true